### ISSUE TITLE
[Discussion] Whether it is possible to list on plugin stores such as curseforge

### ISSUE THREAD

**Issue by LeXwDeX** [blazer404/TargetCharmsRe#1]
As mentioned in the title, I have noticed that this plugin is still being used by some users. So, I would like to ask why not consider listing it on the store? You can add characters like "re" after the plugin's name to indicate that it is a refactored or revised version.

**Comment by blazer404** [comment]
As I already wrote on curseforge, first of all, I support the functionality of the plugin for myself. Secondly, the author of the plugin did not give me permission to support and modify it. Therefore, I believe that by placing it in the store, I will appropriate someone else's work. If the author wants, he can use my changes and publish them himself.
